version: '3.1'

services:
  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"

  odoo:
    image: odoo:17
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "12000:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
